baseURL = "https://mantamburini.github.io/"
locale = "it-it"
title = "Quando scrivere serve"
theme = "hugo-theme-stack"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false

[params]
  author = "Marcello Anselmi Tamburini"
  description = "Quando scrivere serve"
  mainSections = ["chiedi-a-mario"]

[params.sidebar]
  emoji = "📝"
  subtitle = "Metodo per documentare i processi IT"
  compact = false

[params.article]
  math = false
  toc = true
  readingTime = true
  headingAnchor = true
  mermaid.look = "classic"

[params.colorScheme]
  toggle = true
  default = "auto"

[[params.widgets.homepage]]
  type = "search"

[[params.widgets.homepage]]
  type = "archives"
  [params.widgets.homepage.params]
    limit = 10

[[params.widgets.homepage]]
  type = "tag-cloud"
  [params.widgets.homepage.params]
    limit = 10

[[params.widgets.page]]
  type = "search"

[[params.widgets.page]]
  type = "toc"

[[params.widgets.page]]
  type = "tag-cloud"
  [params.widgets.page.params]
    limit = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNos = false
    codeFences = true

[outputs]
  home = ["HTML", "RSS"]
