baseURL = "https://mantamburini.github.io/"
locale = "it-IT"
title = "Instrumenta"
theme = "hugo-bearblog"
author = "Marcello Anselmi Tamburini"
enableRobotsTXT = true

[params]
  description = "Gli strumenti del mestiere, usati ogni giorno."
  dateFormat = "2006-01-02"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[markup]
  [markup.highlight]
    style = "friendly"
    codeFences = true
